name: Update YouTube M3U Playlist

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v5

      - name: Configuration de Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Configuration de Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Installation des dépendances (yt-dlp)
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade yt-dlp

      # Création du fichier cookies à partir du secret GitHub
      - name: Création du fichier cookies
        run: |
          echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Exécution du script de mise à jour
        run: python update_playlist.py

      - name: Suppression du fichier cookies
        if: always()
        run: rm -f cookies.txt

      - name: Commit et Push des modifications
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add playlist.m3u
          git diff --staged --quiet || (git commit -m "Auto-update playlist.m3u [skip ci]" && git push)
