# This is a basic workflow to help you get started with Actions

name: M3U generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 */4 * * *' # S'exécute toutes les 4 heures

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout du dépôt
        uses: actions/checkout@v5

      - name: Configuration de Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Configuration de Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Exécution du script de récupération
        run: |
          pwd
          chmod +x autorun.sh
          ./autorun.sh

      - name: Vérification et Commit des modifications
        run: |
          git add -A
          # Vérifie s'il y a des changements avant de faire le commit
          if git diff-index --quiet HEAD --; then
            echo "Aucune modification détectée. Fin du workflow."
          else
            echo "Modifications détectées. Envoi des mises à jour..."
            git commit -m "Mise à jour automatique des liens M3U"
            git push origin main
          fi
